"""
EZ Gadgets Headset scraper — WooCommerce Store API, with a DOM fallback.

Primary path : /wp-json/wc/store/v1/products?category=<id>&per_page=100
Fallback path: the Woodmart category archive, cards at `.wd-product`

Generated by scrapers/gen_ezgadgets_scrapers.py — edit the generator, not this.

Usage:
  python scrapers/ezgadgets/scrape_headset.py           # print only
  python scrapers/ezgadgets/scrape_headset.py --save    # save JSON to data/raw/
  python scrapers/ezgadgets/scrape_headset.py --dom     # force the fallback
"""

import argparse
import asyncio
import html
import io
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

from playwright.async_api import async_playwright, TimeoutError as PlaywrightTimeout

BASE_URL      = "https://ggezgadgets.com"
CATEGORY_SLUG = "headset"
ARCHIVE_URL   = f"{BASE_URL}/product-category/peripherals/headset/"

# Cloudflare fronts this shop. It served us plain 200s throughout development,
# but the requests still go through a real browser context so that any cookie or
# challenge it does set is carried automatically — the same reason the Ryans
# scraper uses Playwright rather than `requests`.
USER_AGENT = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
              "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36")

# Same stealth payload the Ryans scraper uses. Ryans is Cloudflare-protected too
# and pulls ~7,000 rows per nightly CI sweep, so this combination is known to
# clear Cloudflare from a GitHub Actions IP — it is not a guess.
_STEALTH_SCRIPT = """\
Object.defineProperty(navigator, 'webdriver', {get: () => undefined});
Object.defineProperty(navigator, 'plugins', {get: () => [1,2,3,4,5]});
window.chrome = {runtime: {}};
"""


async def _make_context(browser):
    ctx = await browser.new_context(
        user_agent=USER_AGENT,
        viewport={"width": 1400, "height": 1000},
    )
    await ctx.add_init_script(_STEALTH_SCRIPT)
    return ctx

PAGE_DELAY = 2.5    # seconds between requests — polite crawling
PER_PAGE   = 100    # Store API maximum
MAX_PAGES  = 60     # backstop against a paginator that never terminates
RETRIES    = 3      # attempts per request before giving up on it


class Blocked(Exception):
    """A request failed in a way that must not be mistaken for 'no more data'."""


async def _sleep_backoff(attempt: int) -> None:
    await asyncio.sleep(PAGE_DELAY * (2 ** attempt))


# ---------------------------------------------------------------------------
# Store API (primary)
# ---------------------------------------------------------------------------

async def api_get(page, url: str):
    """GET JSON with fetch() from inside the live page. Returns (status, body).

    Deliberately not `context.request.get()`. That shares cookies but executes
    no JavaScript, so Cloudflare's challenge on /wp-json defeats it — which is
    why the first production run resolved zero categories from a GitHub Actions
    runner while a residential IP worked fine. A same-origin fetch() from the
    page carries the full browser fingerprint and any clearance cookie already
    issued.
    """
    return await page.evaluate(
        """async (u) => {
            try {
                const r = await fetch(u, {
                    credentials: 'include',
                    headers: {'Accept': 'application/json'},
                });
                let body = null;
                try { body = await r.json(); } catch (e) { body = null; }
                return [r.status, body];
            } catch (e) {
                return [0, null];
            }
        }""",
        url,
    )


async def api_get_retrying(page, url: str, what: str):
    """api_get with backoff. Raises Blocked if every attempt fails."""
    last = None
    for attempt in range(RETRIES):
        status, body = await api_get(page, url)
        if status == 200 and body is not None:
            return body
        last = status
        print(f"  [api] HTTP {status} on {what} (attempt {attempt + 1}/{RETRIES})")
        if attempt + 1 < RETRIES:
            await _sleep_backoff(attempt)
    raise Blocked(f"{what} failed after {RETRIES} attempts (last status {last})")


async def resolve_category_id(page, slug: str) -> int | None:
    """Map a category slug to its WordPress term id.

    Returns None only when the slug genuinely is not in the catalogue. A
    transport failure raises Blocked instead, so 'the shop dropped this
    category' can never be confused with 'Cloudflare said no'.
    """
    page_num = 1
    while page_num <= 10:
        rows = await api_get_retrying(
            page,
            f"{BASE_URL}/wp-json/wc/store/v1/products/categories"
            f"?per_page=100&page={page_num}",
            f"categories page {page_num}",
        )
        if not rows:
            return None
        for row in rows:
            if row.get("slug") == slug:
                return row["id"]
        if len(rows) < 100:
            return None
        page_num += 1
        await asyncio.sleep(PAGE_DELAY)
    return None


def money(minor: str | int | None, minor_unit: int) -> float | None:
    """Store API prices are integer minor units: "549900" @ unit 2 -> 5499.00."""
    if minor is None or minor == "":
        return None
    try:
        val = int(minor) / (10 ** minor_unit)
    except (TypeError, ValueError):
        return None
    return val or None


def from_api(p: dict, scraped_at: str) -> dict | None:
    # WordPress stores post titles as HTML, so the API hands back "27&#8243;"
    # and "Keyboard &#038; Mouse". Decode before anything downstream sees it —
    # this name becomes the canonical product name and feeds the fuzzy matcher.
    name = html.unescape(p.get("name") or "").strip()
    if not name:
        return None

    prices = p.get("prices") or {}
    unit = prices.get("currency_minor_unit", 2)
    price = money(prices.get("price"), unit)

    inline_specs = {}
    rng = prices.get("price_range")
    if rng:
        # Variable product: `price` is already the low end. Record the span so
        # the archive shows this was a "from" price, not a single figure.
        lo = money(rng.get("min_amount"), unit)
        hi = money(rng.get("max_amount"), unit)
        if lo and hi and hi != lo:
            inline_specs["price_from"] = lo
            inline_specs["price_max"] = hi

    in_stock = bool(p.get("is_in_stock")) and price is not None
    images = p.get("images") or []

    return {
        "image_url": (images[0].get("src") if images else None) or None,
        "name": name,
        "price_bdt": price,
        "in_stock": in_stock,
        "stock_status": "in_stock" if in_stock else "out_of_stock",
        "product_url": p.get("permalink"),
        "inline_specs": inline_specs,
        "source": "EZGadgets",
        "pc_bundle_only": False,
        "scraped_at": scraped_at,
    }


async def scrape_via_api(page) -> list[dict] | None:
    """Return records, or None if the Store API is unusable (caller falls back).

    Any partial result is discarded rather than returned: a category truncated
    by a block looks exactly like a category that shrank, and the loader cannot
    tell the difference.
    """
    try:
        cat_id = await resolve_category_id(page, CATEGORY_SLUG)
    except Blocked as exc:
        print(f"  [api] {exc}")
        return None
    if cat_id is None:
        print(f"  [api] slug {CATEGORY_SLUG!r} is not in the catalogue")
        return None
    print(f"  [api] category {CATEGORY_SLUG!r} -> id {cat_id}")

    products: list[dict] = []
    seen: set[int] = set()
    scraped_at = datetime.now(timezone.utc).isoformat()

    page_num = 1
    while page_num <= MAX_PAGES:
        url = (f"{BASE_URL}/wp-json/wc/store/v1/products"
               f"?category={cat_id}&per_page={PER_PAGE}&page={page_num}")
        print(f"Fetching page {page_num}: {url}")
        try:
            rows = await api_get_retrying(page, url, f"products page {page_num}")
        except Blocked as exc:
            print(f"  [api] {exc} — discarding {len(products)} partial records")
            return None

        print(f"  Found {len(rows)} products.")
        if not rows:
            break

        for row in rows:
            pid = row.get("id")
            if pid in seen:
                continue
            seen.add(pid)
            rec = from_api(row, scraped_at)
            if rec:
                products.append(rec)

        if len(rows) < PER_PAGE:
            break
        page_num += 1
        await asyncio.sleep(PAGE_DELAY)

    return products


# ---------------------------------------------------------------------------
# DOM archive (fallback)
# ---------------------------------------------------------------------------

def clean_price(raw: str) -> float | None:
    digits = re.sub(r"[^\d.]", "", raw.strip().split("\n")[0])
    try:
        val = float(digits) if digits else None
        return val if val else None
    except ValueError:
        return None


# One evaluate() per card instead of a dozen query_selector round trips.
CARD_JS = """el => {
    const a = el.querySelector('.wd-entities-title a') || el.querySelector('h3 a');
    if (!a) return null;
    const name = a.textContent.trim();
    if (!name) return null;

    const priceEl = el.querySelector('.price');
    const amounts = priceEl
        ? [...priceEl.querySelectorAll('.woocommerce-Price-amount')].map(e => e.textContent.trim())
        : [];
    const insEl = priceEl ? priceEl.querySelector('ins') : null;
    const insAmount = insEl
        ? (insEl.querySelector('.woocommerce-Price-amount') || insEl).textContent.trim()
        : null;

    // Woodmart lazy-loads listing images and, when a product has a gallery,
    // renders slides carrying data-image-url with no <img> at all.
    let image = '';
    for (const img of el.querySelectorAll('img')) {
        const v = img.getAttribute('data-src') || img.getAttribute('data-lazy')
               || img.getAttribute('src') || '';
        if (!v || v.startsWith('data:') || v.toLowerCase().endsWith('.svg')) continue;
        try { image = new URL(v, document.baseURI).href; } catch (e) {}
        if (image) break;
    }
    if (!image) {
        const slide = el.querySelector('.wd-product-grid-slide[data-image-url]');
        if (slide) {
            try { image = new URL(slide.getAttribute('data-image-url'), document.baseURI).href; }
            catch (e) {}
        }
    }

    const cls = el.className || '';
    return {
        name,
        product_url: a.href || null,
        amounts,
        ins_amount: insAmount,
        is_variable: cls.includes('product-type-variable'),
        out_of_stock: cls.includes('outofstock'),
        image_url: image || null,
    };
}"""


def pick_price(rec: dict) -> tuple[float | None, float | None]:
    """Return (price, price_max). price_max is set only for a variable range.

    Read the amount elements, never `.price` text: the sale markup interleaves
    screen-reader copy ("Original price was: ...") with the numbers.
      plain    -> one amount
      on sale  -> <del> old, <ins> new; take <ins>
      variable -> "low - high"; take low, the "from" price, and keep high
    """
    if rec.get("ins_amount"):
        price = clean_price(rec["ins_amount"])
        if price:
            return price, None

    amounts = [p for p in (clean_price(a) for a in rec.get("amounts") or []) if p]
    if not amounts:
        return None, None
    if rec.get("is_variable") and len(amounts) > 1:
        return min(amounts), max(amounts)
    return amounts[0], None


async def scrape_archive_page(page, url: str) -> list[dict]:
    """Records on one archive page. Raises Blocked if the grid never renders.

    There is no 'empty page' case here: the caller reads the real page count
    from page 1's pagination and never requests a page past it, so a missing
    product grid always means blocked. Guessing 'empty vs blocked' from the
    markup was tried and got it wrong — a one-page category's page 2 was read as
    a block, which failed 14 complete scrapes.
    """
    await page.goto(url, wait_until="domcontentloaded", timeout=60_000)
    try:
        await page.wait_for_selector(".wd-product", timeout=15_000)
    except PlaywrightTimeout:
        raise Blocked(f"no product grid at {url}")

    for y in [400, 900, 1600]:
        await page.evaluate(f"window.scrollTo(0, {y})")
        await page.wait_for_timeout(300)
    await page.wait_for_timeout(500)

    products = []
    scraped_at = datetime.now(timezone.utc).isoformat()

    for card in await page.query_selector_all(".wd-product"):
        rec = await card.evaluate(CARD_JS)
        if not rec:
            continue

        price, price_max = pick_price(rec)
        in_stock = (not rec["out_of_stock"]) and price is not None

        inline_specs = {}
        if price_max is not None:
            inline_specs["price_from"] = price
            inline_specs["price_max"] = price_max

        products.append({
            "image_url": rec["image_url"],
            "name": rec["name"],
            "price_bdt": price,
            "in_stock": in_stock,
            "stock_status": "in_stock" if in_stock else "out_of_stock",
            "product_url": rec["product_url"],
            "inline_specs": inline_specs,
            "source": "EZGadgets",
            "pc_bundle_only": False,
            "scraped_at": scraped_at,
        })

    return products


async def _fetch_one_page(browser, page_num: int, want_count: bool):
    """Fetch one archive page in a **fresh browser context**, with retries.

    Reusing one context across pages makes Cloudflare re-issue its challenge and
    the scrape dies — the same behaviour documented for Ryans in CLAUDE.md. A
    context per page is slower and reliable; Ryans pulls ~7,000 rows a night
    from CI this way.
    """
    url = ARCHIVE_URL if page_num == 1 else f"{ARCHIVE_URL}page/{page_num}/"
    print(f"Scraping page {page_num}: {url}")

    for attempt in range(RETRIES):
        ctx = await _make_context(browser)
        page = await ctx.new_page()
        try:
            found = await scrape_archive_page(page, url)
            total = await page_count(page) if want_count else None
            return found, total
        except Blocked as exc:
            print(f"  [dom] {exc} (attempt {attempt + 1}/{RETRIES})")
            if attempt + 1 < RETRIES:
                await _sleep_backoff(attempt)
        finally:
            await ctx.close()

    raise Blocked(f"page {page_num} still blocked after {RETRIES} attempts")


async def page_count(page) -> int:
    """Highest page number in the archive's pagination (1 if unpaginated)."""
    return await page.evaluate(
        """() => {
            const ns = [...document.querySelectorAll('.page-numbers')]
                .map(a => parseInt(a.textContent.trim()))
                .filter(n => !isNaN(n));
            return ns.length ? Math.max(...ns) : 1;
        }"""
    )


async def scrape_via_dom(browser) -> list[dict]:
    """Page through the category archive, a fresh context per page.

    Page 1 reports how many pages exist, and we fetch exactly that many. Nothing
    beyond the last page is ever requested, so there is no ambiguous empty page
    to misread, and any failure inside 1..N is a genuine block that raises
    rather than quietly returning a short list.
    """
    first, total = await _fetch_one_page(browser, 1, want_count=True)
    total = min(total or 1, MAX_PAGES)
    print(f"  Found {len(first)} products.  ({total} page(s) in this category)")

    seen: set[str] = set()
    products: list[dict] = []
    for rec in first:
        seen.add(rec["product_url"])
        products.append(rec)

    for page_num in range(2, total + 1):
        await asyncio.sleep(PAGE_DELAY)
        found, _ = await _fetch_one_page(browser, page_num, want_count=False)
        print(f"  Found {len(found)} products.")
        fresh = [p for p in found if p["product_url"] not in seen]
        seen.update(p["product_url"] for p in fresh)
        products.extend(fresh)

    return products


# ---------------------------------------------------------------------------

async def main(save: bool = False, force_dom: bool = False):
    async with async_playwright() as pw:
        browser = await pw.chromium.launch(
            headless=True,
            args=["--disable-blink-features=AutomationControlled"],
        )

        all_products = None
        if not force_dom:
            # Land on a real page first so Cloudflare issues its cookies, and so
            # the API fetch runs same-origin from a page it has already cleared.
            ctx = await _make_context(browser)
            page = await ctx.new_page()
            await page.goto(ARCHIVE_URL, wait_until="domcontentloaded", timeout=90_000)
            await page.wait_for_timeout(2000)
            all_products = await scrape_via_api(page)
            await ctx.close()

        if all_products is None:
            if not force_dom:
                print("\n" + "!" * 62)
                print("!! Store API unavailable — falling back to DOM scraping.")
                print("!! Expected on datacenter IPs: Cloudflare answers /wp-json")
                print("!! with 403 from GitHub Actions while allowing it locally.")
                print("!! A 403 here is normal in CI; anything else is worth a look.")
                print("!" * 62 + "\n")
            try:
                all_products = await scrape_via_dom(browser)
            except Blocked as exc:
                await browser.close()
                # Exit non-zero. run_pipeline treats a failed scrape as non-fatal
                # and moves on, which is right — but the category must be
                # reported as failed, never loaded as a truncated list.
                sys.exit(f"\nFAILED: {exc}\nRefusing to load a partial category.")

        await browser.close()

    if save:
        out_dir = Path("data/raw")
        out_dir.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        out_path = out_dir / f"ezgadgets_headset_{timestamp}.json"
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(all_products, f, ensure_ascii=False, indent=2)
        print(f"\nSaved {len(all_products)} records -> {out_path}")

    in_stock = [p for p in all_products if p["in_stock"] and p["price_bdt"]]
    print(f"\nTotal: {len(all_products)} | In stock: {len(in_stock)}")
    if in_stock:
        cheapest = min(in_stock, key=lambda p: p["price_bdt"])
        print(f"Cheapest: {cheapest['name'][:70]}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Scrape EZ Gadgets Headset listings")
    parser.add_argument("--save", action="store_true")
    parser.add_argument("--dom", action="store_true",
                        help="Skip the Store API and scrape the category archive")
    args = parser.parse_args()
    asyncio.run(main(save=args.save, force_dom=args.dom))
